name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    branches: [ "tmp" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: install required deps
      run: sudo apt-get update \
            sudo apt-get install -y \
            automake \
            autoconf \
            libtool \
            pkg-config \
            build-essential
    - name: configure
      run: ./configure
    - name: Build with make
      run: make
    - name: (Optional) Install the package
      run: make install
    - name: (Optional) Post-installation cleanup
      run: ./cleanup.sh
    - name: (Optional) Copy config files
      run: ./copy-config.sh
