name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: run autoreconf
      run: autoreconf --install
    - name: Make sure all is good
      run: ./configure
    - name: Build with make
      run: make
    - name: (Optional) Install the package
      run: make install
    - name: (Optional) Post-installation cleanup
      run: ./cleanup.sh
    - name: (Optional) Copy config files
      run: ./copy-config.sh
