name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: arch-rolling
    
    steps:
    - uses: actions/checkout@v4
    - name: Make sure all is good
      run: ./configure
    - name: Build with make
      run: make
    - name: Install the package
      run: make install
