name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    branches: [ "tmp" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: ./configure
    - name: Build with make
      run: make
    - name: Install the package
      run: make install
    - name: Post-installation cleanup
      run: ./cleanup.sh
    - name: Copy config files
      run: ./copy-config.sh
